apiVersion: v1
kind: Service
metadata:
  name: k8stest-service
spec:
  selector:
    app: k8stest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007
  type: NodePort
