apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-node-deployment
  labels:
    app: k8stest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8stest
  template:
    metadata:
      labels:
        app: k8stest
    spec:
      containers:
      - name: k8stest
        imagePullPolicy: Always
        image: mdshajib/k8stest
        ports:
          - containerPort: 3000